services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: https://daily.dochoitinphat.com
